import React, { useState } from 'react';
import { HistoryItem } from '../types';
import { 
  Clock, TrendingDown, TrendingUp, Award, Users, ShieldAlert,
  Camera, CheckCircle2, XCircle, ThumbsUp, ThumbsDown, Check, Eye, EyeOff, MapPin
} from 'lucide-react';

interface HistoricTabProps {
  history: HistoryItem[];
  onVoteApproval?: (historyId: string, status: 'APPROVED' | 'REJECTED') => void;
}

export default function HistoricTab({ history, onVoteApproval }: HistoricTabProps) {
  const [zoomedPhotoId, setZoomedPhotoId] = useState<string | null>(null);

  // Total points generated by community
  const totalPoints = history.reduce((sum, item) => sum + item.userPoints, 0);

  return (
    <div className="w-full flex flex-col pb-24 font-sans animate-in fade-in duration-200">
      
      {/* Overview Stat Board Panel */}
      <section className="bg-blue-800 text-white rounded-xl p-5 mb-6 shadow-md border border-blue-900 relative overflow-hidden">
        
        {/* Glow vector effect */}
        <div className="absolute -bottom-10 -right-10 w-40 h-40 bg-white/5 rounded-full filter blur-xl"></div>
        
        <div className="flex items-center gap-2 mb-3">
          <Award className="w-5 h-5 text-sky-300" />
          <h2 className="text-xs font-bold uppercase tracking-wider font-mono text-sky-200">
            Comunidade AbastecePMW
          </h2>
        </div>

        <h3 className="text-2xl font-extrabold tracking-tight mb-4">
          Unidos pelo Melhor Preço
        </h3>

        <div className="grid grid-cols-2 gap-4 pt-1 bg-blue-950/30 p-3 rounded-lg border border-blue-700/20">
          <div>
            <p className="text-[10px] text-sky-200 uppercase font-mono font-bold tracking-wider">
              Atualizações
            </p>
            <p className="text-xl font-extrabold font-sans mt-0.5">
              {history.length} registradas
            </p>
          </div>
          <div className="border-l border-blue-700/50 pl-4">
            <p className="text-[10px] text-sky-200 uppercase font-mono font-bold tracking-wider">
              Créditos Distribuídos
            </p>
            <p className="text-xl font-extrabold font-mono text-sky-200 mt-0.5">
              +{totalPoints} PTS
            </p>
          </div>
        </div>

        <div className="text-[11px] text-sky-100 flex gap-1.5 mt-3 leading-tight font-sans">
          <span className="font-semibold text-sky-300">📢 Nota:</span>
          <span>Envie uma foto do visor físico para ganhar o dobro de pontos e aprovar as tarifas na hora!</span>
        </div>
      </section>

      {/* Timeline Section Header */}
      <div className="flex items-center justify-between mb-4">
        <div className="flex items-center gap-2">
          <Users className="w-5 h-5 text-gray-700" />
          <h3 className="font-bold text-lg text-gray-905 tracking-tight font-sans">
            Atividades Recentes
          </h3>
        </div>
        <span className="text-[10px] bg-slate-100 text-slate-600 px-2 py-1 rounded-sm font-bold font-mono uppercase tracking-wide">
          Auditoria Ativa
        </span>
      </div>

      {/* History Feed List */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        {history.length === 0 ? (
          <div className="py-12 bg-white rounded-xl border border-gray-200 text-center text-gray-500 text-sm md:col-span-2">
            Nenhuma atividade registrada ainda.
          </div>
        ) : (
          history.map((item) => {
            const isDiscount = item.newPrice < item.oldPrice;

            return (
              <div 
                key={item.id}
                className="bg-white rounded-xl border border-gray-150 p-4 shadow-xs flex flex-col gap-3.5 hover:border-gray-250 transition-all"
              >
                {/* Upper line: contributor profile info */}
                <div className="flex items-start gap-3">
                  <span className="w-9 h-9 rounded-xl bg-blue-50 text-blue-800 flex items-center justify-center border border-blue-100 shrink-0">
                    <MapPin className="w-5 h-5 text-blue-850" />
                  </span>

                  <div className="flex-1 min-w-0">
                    <div className="flex items-center justify-between gap-2">
                      <h4 className="font-extrabold text-gray-900 text-[14px] font-sans tracking-tight leading-snug truncate">
                        {item.stationName}
                      </h4>
                      <span className="text-[9px] text-gray-400 font-mono shrink-0 mt-0.5">
                        {item.timestamp}
                      </span>
                    </div>

                    <p className="text-[11px] text-gray-500 mt-0.5 font-sans leading-normal">
                      Tarifa de <strong className="text-gray-800 font-medium">{item.fuelType}</strong> informada por <span className="text-gray-650 font-medium font-sans">{item.userName}</span>
                    </p>
                  </div>

                  {/* Points Indicator badge */}
                  <div className="bg-blue-50/50 text-blue-800 border border-blue-100 text-right py-1 px-2.5 rounded shrink-0">
                    <p className="text-[11px] font-extrabold font-mono leading-none tracking-tight">+{item.userPoints}</p>
                    <p className="text-[7px] font-bold text-blue-600 uppercase tracking-widest font-mono mt-0.5">PTS</p>
                  </div>
                </div>

                {/* Transition details price block and discount tag */}
                <div className="flex items-center justify-between gap-1 bg-gray-50/75 p-2 rounded-lg border border-gray-100/80">
                  <div className="flex items-center gap-1.5 font-mono">
                    <span className="text-xs text-gray-400 line-through">R$ {item.oldPrice.toFixed(2)}</span>
                    <span className="text-gray-300 font-mono">→</span>
                    <span className={`text-sm font-extrabold ${isDiscount ? 'text-emerald-700' : 'text-rose-700'}`}>
                      R$ {item.newPrice.toFixed(2)} / L
                    </span>
                  </div>

                  <div className={`flex items-center gap-0.5 text-[9px] uppercase font-bold tracking-wider font-mono ${
                    isDiscount ? 'text-emerald-700 bg-emerald-50 px-2 py-0.5 rounded border border-emerald-100' : 'text-rose-600 bg-rose-50 px-2 py-0.5 rounded border border-rose-100'
                  }`}>
                    {isDiscount ? (
                      <>
                        <TrendingDown className="w-3.5 h-3.5 text-emerald-600 shrink-0" /> Diminuiu
                      </>
                    ) : (
                      <>
                        <TrendingUp className="w-3.5 h-3.5 text-rose-600 shrink-0" /> Aumentou
                      </>
                    )}
                  </div>
                </div>

                {/* Verified Photo Comprovante Attachments with dynamic labels */}
                {item.photoUrl && (
                  <div className="border border-slate-100 rounded-lg p-2.5 bg-slate-50/50 space-y-2">
                    <div className="flex items-center justify-between text-[11px]">
                      <span className="text-gray-600 flex items-center gap-1 font-bold">
                        <Camera className="w-3.5 h-3.5 text-blue-700" /> Foto Comprovante:
                      </span>
                      <button
                        onClick={() => setZoomedPhotoId(zoomedPhotoId === item.id ? null : item.id)}
                        className="text-[10px] text-blue-800 font-bold font-mono hover:underline flex items-center gap-1 cursor-pointer"
                      >
                        {zoomedPhotoId === item.id ? (
                          <>Ocultar <EyeOff className="w-3 h-3" /></>
                        ) : (
                          <>Verificar Ampliado <Eye className="w-3 h-3" /></>
                        )}
                      </button>
                    </div>

                    {/* Image Box Container */}
                    <div className="relative overflow-hidden rounded-md bg-white border border-gray-200">
                      <img 
                        src={item.photoUrl} 
                        alt="Preço no posto" 
                        className={`w-full object-cover transition-all duration-300 ${
                          zoomedPhotoId === item.id ? 'h-64 object-contain bg-slate-900' : 'h-24'
                        }`} 
                      />
                    </div>

                    {/* Status audit badges display */}
                    <div className="flex items-center justify-between pt-1 border-t border-slate-100">
                      <span className="text-[9px] font-bold text-gray-400 uppercase font-mono">
                        MODERADO POR VOTOS
                      </span>

                      {item.status === 'PENDING' && (
                        <span className="bg-amber-50 text-amber-700 text-[10px] font-bold uppercase tracking-wide px-2 py-0.5 border border-amber-200 rounded flex items-center gap-1 font-mono">
                          <span className="w-1.5 h-1.5 rounded-full bg-amber-500 animate-pulse"></span>
                          Em Auditoria
                        </span>
                      )}

                      {item.status === 'APPROVED' && (
                        <span className="bg-emerald-50 text-[#006c49] text-[10px] font-bold uppercase tracking-wide px-2 py-0.5 border border-emerald-205 rounded flex items-center gap-1 font-mono">
                          <CheckCircle2 className="w-3.5 h-3.5 text-emerald-600 shrink-0" />
                          Aprovado ✓
                        </span>
                      )}

                      {item.status === 'REJECTED' && (
                        <span className="bg-rose-50 text-rose-700 text-[10px] font-bold uppercase tracking-wide px-2 py-0.5 border border-rose-200 rounded flex items-center gap-1 font-mono">
                          <XCircle className="w-3.5 h-3.5 text-rose-605 shrink-0" />
                          Recusado ✗
                        </span>
                      )}
                    </div>

                    {/* Collaborative Vote Panel inside card */}
                    {item.status === 'PENDING' && onVoteApproval && (
                      <div className="bg-blue-50/50 p-2.5 rounded-md border border-blue-100 flex flex-col gap-1.5 mt-2 animate-pulse">
                        <p className="text-[10px] text-blue-900 leading-tight">
                          <strong>👥 Auditoria da Comunidade:</strong> Esta foto corresponde aos preços informados? Ajude a auditar:
                        </p>
                        <div className="flex gap-2">
                          <button
                            type="button"
                            onClick={() => onVoteApproval(item.id, 'APPROVED')}
                            className="flex-1 h-8 bg-emerald-700 hover:bg-emerald-800 text-white font-bold text-[10px] rounded flex items-center justify-center gap-1 transition-all cursor-pointer shadow-xs active:scale-95"
                          >
                            <ThumbsUp className="w-3 h-3 text-white fill-white" /> Corretos (Aprovar)
                          </button>
                          <button
                            type="button"
                            onClick={() => onVoteApproval(item.id, 'REJECTED')}
                            className="h-8 px-3 bg-white hover:bg-rose-50 border border-rose-200 text-rose-600 font-bold text-[10px] rounded flex items-center justify-center gap-1 transition-all cursor-pointer active:scale-95"
                          >
                            <ThumbsDown className="w-3 h-3" /> Incorretos
                          </button>
                        </div>
                      </div>
                    )}
                  </div>
                )}

              </div>
            );
          })
        )}
      </div>

    </div>
  );
}
